# PyTorch を練習してみる。
あああ、ここに日記をグダグダ書いても良いかも知れない。結局 github に上げることになるんだもんね。

In [11]:
import numpy as np
import torch
import torch.nn.functional as F
device = torch.device('cpu')

a = np.array \
( [ [ -0.1,  0.0, 0.1, 0.2 ]
  , [ -0.3, -0.1, 0.1, 0.3 ] ]
, dtype=np.float32)
t = torch.from_numpy(a).clone()

F.relu(t)

tensor([[0.0000, 0.0000, 0.1000, 0.2000],
        [0.0000, 0.0000, 0.1000, 0.3000]])

In [16]:
import torch.nn as nn

class MyNN(nn.Module):
    def __init__(self):
        super(MyNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 2, kernel_size=3)
    def forward(self, x):
        return self.conv1(x)

np.random.seed(0)
torch.manual_seed(0)

n = MyNN()
n.conv1.weight

Parameter containing:
tensor([[[[-0.0025,  0.1788, -0.2743],
          [-0.2453, -0.1284,  0.0894],
          [-0.0066,  0.2643, -0.0296]]],


        [[[ 0.0882, -0.1007, -0.0655],
          [-0.3184, -0.2208, -0.1374],
          [ 0.0123,  0.1318,  0.2000]]]], requires_grad=True)

In [17]:
n.conv1.weight[0][0][0][0] = 1.0
n.conv1.weight

Parameter containing:
tensor([[[[ 1.0000,  0.1788, -0.2743],
          [-0.2453, -0.1284,  0.0894],
          [-0.0066,  0.2643, -0.0296]]],


        [[[ 0.0882, -0.1007, -0.0655],
          [-0.3184, -0.2208, -0.1374],
          [ 0.0123,  0.1318,  0.2000]]]], grad_fn=<CopySlices>)

In [24]:
n.conv1.weight = \
nn.Parameter \
( torch.from_numpy \
  ( np.zeros([2, 1, 3, 3]).astype(np.float32) ) )
n.conv1.weight

Parameter containing:
tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]], requires_grad=True)

In [23]:
n(torch.from_numpy(np.zeros([4, 1, 3, 5], dtype=np.float32)))

tensor([[[[-0.2260, -0.2260, -0.2260]],

         [[-0.1452, -0.1452, -0.1452]]],


        [[[-0.2260, -0.2260, -0.2260]],

         [[-0.1452, -0.1452, -0.1452]]],


        [[[-0.2260, -0.2260, -0.2260]],

         [[-0.1452, -0.1452, -0.1452]]],


        [[[-0.2260, -0.2260, -0.2260]],

         [[-0.1452, -0.1452, -0.1452]]]], grad_fn=<MkldnnConvolutionBackward>)